background_opacity 0.80
hide_window_decorations yes

font_size 13 
font_family JetBrainsMono

# cursor_trail 10
# cursor_trail_decay 0.1 0.3

remember_window_size  yes
initial_window_width  1000
initial_window_height 800
