general {
    gaps_in = 2
    gaps_out = 9 
    border_size = 1
    col.active_border = rgb(879A39) 
    col.inactive_border = rgb(100F0F) 
    resize_on_border = false
    allow_tearing = true
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1
    shadow {
        enabled = false
        range = 8
        render_power = 150
        color = rgb(0, 0, 0) 
    }
    blur {
        enabled = true
        size = 1
        passes = 2
        vibrancy = 0.1696
    }
}

animations {
    enabled = no 
}
