source = ~/.config/hypr/modules/env.conf
exec-once = $run wl-paste --type text --watch cliphist store
exec-once = $run wl-paste --type image --watch cliphist store
exec-once = $run discord
exec-once = ~/.config/scripts/reload_wallpaper.sh
