source = ~/.config/hypr/modules/env.conf
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = discord
exec-once = ~/.config/scripts/reload_wallpaper.sh
