$mainMod = SUPER
source = ~/.config/hypr/modules/env.conf
bind = $mainMod, T, exec, $run $terminal
bind = $mainMod, Q, exec, $run $webbrowser
bind = $mainMod, C, killactive,
bind = $mainMod, E, exec, $run $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, G, layoutmsg, togglesplit # dwindle
bind = $mainMod SHIFT, Delete, exec, ~/.config/rofi/powermenu.sh

#Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod, H, workspace, e-1
bind = $mainMod, L, workspace, e+1

#Move focused to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

#Change focus
bind = $mainMod CTRL, l, movefocus, r
bind = $mainMod CTRL, h, movefocus, l
bind = $mainMod CTRL, k, movefocus, u
bind = $mainMod CTRL, j, movefocus, d


#Resize window
bind = $mainMod, m, submap, resize

submap = resize

binde = CTRL, l, resizeactive, 10 0
binde = CTRL, h, resizeactive, -10 0
binde = CTRL, k, resizeactive, 0 -10
binde = CTRL, j, resizeactive, 0 10

bind = , escape, submap, reset

submap = reset

#Special workspace bindings
bind = $mainMod, B, togglespecialworkspace, magic
bind = $mainMod SHIFT, B, movetoworkspace, special:magic

#Mouse bindings
bind = $mainMod, mouse_down, workspace, e-1
bind = $mainMod, mouse_up, workspace, e+1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

#Alt tab behavior
bind = $mainMod, Tab, cyclenext,           # change focus to another window
bind = $mainMod, Tab, bringactivetotop,    # bring it to the top

#Clipboard
bind = $mainMod, Y, exec, ~/.config/rofi/cliphistory.sh 

#Color picker
bind = $mainMod SHIFT, C, exec, $run hyprpicker -a 

#Screenshot
#bind = , Print, exec, grim -g "$(slurp -d)" - | wl-copy
bind = , Print, exec, $run hyprshot -z -m region --freeze -o $HOME/Pictures/Screenshots/

#Book reader
bind = $mainMod SHIFT, r, exec, $run $terminal ~/.config/scripts/reader.sh

# Wallpaper selector
bind = $mainMod, w, exec, ~/.config/rofi/wallpaper-sel.sh

#Gamma and Temperature
bind = $mainMod, SHIFT t, submap, gandt

#Reset waybar
bind = $mainMod SHIFT, w, exec, killall waybar; $run waybar

