dwindle {
    pseudotile = true  
    preserve_split = true # You probably want this
}


misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}


# windowrule = float on, match:class thunar
# windowrule = size 800 600, match:class thunar
# windowrule = float on, match:title File Upload
# windowrule = size 800 600,match:title File Upload
#
# windowrule = suppress_event maximize, match:class *
