#workspace = 1, gapsin:2, gapsout:200

#workspace = f[1], gapsout:0, gapsin:0
workspace = 1, monitor:VGA-1
workspace = 2, monitor:VGA-1
workspace = 3, monitor:VGA-1
workspace = 4, monitor:VGA-1
workspace = 5, monitor:VGA-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1  
