return {
    {
        "rebelot/kanagawa.nvim",
        lazy = false,
        config=function ()
            vim.cmd.colorscheme("nord")
        end
    },
    {
        "ellisonleao/gruvbox.nvim",
    },
    {
        "slugbyte/lackluster.nvim",
    },
    {
        "folke/tokyonight.nvim",
    },
    {
        "rose-pine/neovim",
    },
    {
        "rebelot/kanagawa.nvim",
    },
    {
        "vague2k/vague.nvim",
    },
    {
        "deparr/tairiki.nvim",
    },
    {
        "AlessandroYorba/Alduin",
    },
    {
        "chriskempson/vim-tomorrow-theme",
    },
    {
        "savq/melange-nvim",
    },
    {
        "arcticicestudio/nord-vim",
    },
}
